version: '3'
services:
  db:
    image: mysql
    container_name: mysqlprod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - 3307:3306
    networks:
      - backend
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: spring-boot-app
    ports:
      - 8081:8080
    depends_on:
      - db
    networks:
      - backend
networks:
  backend: